-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.traceability_logs
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    event_date_time TEXT NOT NULL,
    event_level character varying(100) COLLATE pg_catalog."default" NOT NULL,
    correlation_id TEXT NOT NULL,
    machine_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    event_message text COLLATE pg_catalog."default" NOT NULL,
    error_source character varying(100) COLLATE pg_catalog."default",
    error_class character varying(100) COLLATE pg_catalog."default",
    error_method text COLLATE pg_catalog."default",
    error_message text COLLATE pg_catalog."default",
    inner_error_message text COLLATE pg_catalog."default",
    CONSTRAINT traceability_logs_pkey PRIMARY KEY (id)
    );
END;